In [2]:
import pandas as pd
import numpy as np
import os
import re

In [8]:
os.system('jupyter nbconvert --to script Lexicons.ipynb')
from Lexicons import *
abc()

rows=[[10, "abc vv"], [20, "abc(10m 9s) <br>"], [30, "abc 2"], [20, "dbc<br>"], [20, ""], [37, np.nan], [30, "ghi"]]
df = pd.DataFrame(rows, columns=["Id", "Text"])
df[df["Text"] != ""].head()
df.reset_index(drop=True, inplace=True)
df.head(20)
1 not in set(df["Id"])
print(set(df["Id"]))
#df.reset_index(drop=True, inplace=True)
print("m" in df.index.names)
print(type(df["Text"]))

['TRUE', 'True', 'true', 'Yes', 'yes']
{10, 20, 37, 30}
False
<class 'pandas.core.series.Series'>


In [5]:
df_filter = df[(df["Text"].notnull()) & (df["Text"] != "")]
df_filter.head(10)
print(df_filter.iloc[:,0])
print(isinstance(None, pd.DataFrame))
print(len(df_filter), df_filter.shape[0])

0    10
1    20
2    30
3    20
6    30
Name: Id, dtype: int64
False
5 5


In [8]:
import re
for index, row in df_filter.iterrows():
    posn = row['Text'].find("bc")+len("bc")
    df_filter['Text'][index] = re.sub('<.*>|\(.*\)', '', row['Text'][posn:])
df_filter.head(10)

<ipython-input-8-4d4ae656960d>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['Text'][index] = re.sub('<.*>|\(.*\)', '', row['Text'][posn:])
C:\Users\sjskd\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3343: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


Id Text
0  10   vv
1  20     
2  30    2
3  20     
6  30   hi

In [9]:
df_filter = df_filter[df_filter["Text"].apply(lambda text: text not in set(["abc", "def"]))]
print(df_filter)

   Id Text
6  30  ghi


In [2]:
df.loc[df.shape[0]] = ([np.nan] * (len(df.columns) - 1)+["mno"])
df.loc[df.shape[0]] = ([np.nan] * (len(df.columns) - 1)+["ghi"])
df.loc[df.shape[0]] = ([np.nan] * (len(df.columns) - 1)+["opq"])
#df = pd.DataFrame(np.insert(df.values, 0, values=[[np.nan] * (len(df.columns) - 1)]+["mno"], axis=1))
#df["Text"] = pd.Series(cols)
df.head(20)

NameError: name 'np' is not defined

In [3]:
df[df["Id"] == 20].iloc[0]["Text"]

'def'

In [4]:
print(df.shape)
for index, row in df.iterrows():
    print(index)

(3, 2)
0
1
2


In [6]:
df.Id.unique()

array([10, 20, 30], dtype=int64)

In [2]:
from datetime import date, datetime, timedelta
from dateutil.relativedelta import relativedelta
current_time = datetime.now()
print(current_time.date()+ relativedelta(years=+2))
print(current_time.date()+ timedelta(days=+1))
print(current_time.date()- relativedelta(months=+4)+ relativedelta(months=+6))
print(current_time.date().weekday())
print(current_time.date().day)
from_index, to_index = 5,6
print(from_index, to_index)
for i in range(0,0):
    print(i)

2023-06-21
2021-06-22
2021-08-21
0
21
5 6


In [6]:
from datetime import date, datetime, timedelta
from dateutil import parser
get_ipython().run_line_magic('cd', '"C:/MY FILES/Demos"')
parser.parse("5/15/2020  5:48:41 AM").date()
datetime.now().date().replace(day=1)


C:\MY FILES\Demos


datetime.date(2020, 12, 1)

In [3]:
from datetime import date, datetime, timedelta
start_date = datetime(2020, 1, 1).date()
start_date < date.today()
print(date.today()-timedelta(days=30))

2021-01-08


In [75]:
import scipy.stats
import math
from scipy.special import softmax
from sklearn.preprocessing import normalize
X = [0.25, 0.25, 0.25, 0.25]
X = [0.2, 0.2, 0.2, 0.2, 0.2]
X = [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125]
X = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
X = [0.9, 0.05, 0.0, 0.025, 0.0, 0.025, 0, 0, 0]
X = [0.9, 0.1]
print(max(X))
test_entropy = scipy.stats.entropy(X)
print(test_entropy)
print(sum([-p*math.log2(p) if p > 0 else 0.0 for p in normalize([X])[0]]))

0.9
0.3250829733914482
0.359833950782112


In [20]:
text_series = df["Text"].value_counts()
print(text_series)
print(len(text_series))
if "abc" in text_series.index:
    print(text_series["abc"])

abc    3
def    1
ghi    1
       1
Name: Text, dtype: int64
4
3


In [15]:
import re
s = "abc < 67 r $ 2 a> (65m 10s) yy"
re.sub('<.*>|\(.*\)', '', s)

'abc   yy'

In [12]:
import nltk
tokens = nltk.word_tokenize("cat sat mat")
print("Parts of Speech: ", nltk.pos_tag(tokens))

Parts of Speech:  [('cat', 'NN'), ('sat', 'VBD'), ('mat', 'NN')]


In [1]:
import spacy
nlp = spacy.load('en')
sent = "I shot an elephant"
doc=nlp(sent)

sub_toks = [tok for tok in doc if (tok.dep_ == "nsubj") ]

print(sub_toks) 

OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

In [12]:
x = [2,3, "we"] + [4,5]
print(x)

[2, 3, 'we', 4, 5]


In [73]:
x = ""
if not x:
    print("sd")

sd


In [1]:
from spellchecker import SpellChecker

spell = SpellChecker()

# find those words that may be misspelled
misspelled = spell.unknown(['something', 'is', 'hapenning', 'here'])
spelled = spell.known(['something', 'is', 'hapenning', 'here'])
print(spelled)

for word in misspelled:
    # Get the one `most likely` answer
    print(spell.correction(word))

    # Get a list of `likely` options
    print(spell.candidates(word))

{'here', 'something', 'is'}
happening
{'henning', 'penning', 'happening'}


In [25]:
x = 'something bafd'
y = x.split(' ')
if len(spell.unknown([y[0], y[1]])) == 0:
    print(x)

In [56]:
str(99.9)

'99.9'

In [3]:
"Ab. F".replace(".", "").lower()
max([2,3.4, 1.2])

3.4

In [13]:
import re
delim = "How can I care for you today?"
text = '<p align="center">Chat Started: Monday, November 02, 2020, 08:49:45 (-0500)</p>( 2s ) Hope: Hi, welcome to AdventHealth! I’m here to help you with any of the following options or to connect you with additional support.<br>( 4s ) Hope: What would you like help with?<br>( 6s ) Hope: {ChatWindowButton:COVID-19 Testing Reservations,Get Care Now,Access Medical Records,Talk with a Care Advocate}<br>( 13s ) Visitor: COVID-19 Testing Reservations<br>( 15s ) Hope: I’m happy to provide testing information in your area. What state do you live in?<br>( 17s ) Hope: {ChatWindowButton:Florida,Kansas,North Carolina,Other}<br>( 18s ) Visitor: Florida<br>( 20s ) Hope: We’re currently offering limited COVID-19 testing, including PCR and antigen testing, at all Florida Centra Care locations.<br>( 22s ) Hope: We recommend scheduling an appointment for a provider visit and test on our website at CentraCare.AdventHealth.com/urgent-care<br>( 24s ) Hope: What would you like help with?<br>( 26s ) Hope: {ChatWindowButton:COVID-19 Testing Reservations,Get Care Now,Access Medical Records,Talk with a Care Advocate}<br>( 30s ) Visitor: How much is the COVID test<br>( 33s ) Hope: You previously asked about Florida. I&#39;m happy to give you information about other areas.<br>( 35s ) Hope: I’m happy to provide testing information in your area. What state do you live in?<br>( 36s ) Hope: {ChatWindowButton:Florida,Kansas,North Carolina,Other}<br>( 38s ) Visitor: Florida<br>( 40s ) Hope: We’re currently offering limited COVID-19 testing, including PCR and antigen testing, at all Florida Centra Care locations.<br>( 42s ) Hope: We recommend scheduling an appointment for a provider visit and test on our website at CentraCare.AdventHealth.com/urgent-care<br>( 44s ) Hope: What would you like help with?<br>( 46s ) Hope: {ChatWindowButton:COVID-19 Testing Reservations,Get Care Now,Access Medical Records,Talk with a Care Advocate}<br>( 50s ) Visitor: COVID-19 Testing Reservations<br>( 52s ) Hope: You previously asked about Florida. I&#39;m happy to give you information about other areas.<br>( 54s ) Hope: I’m happy to provide testing information in your area. What state do you live in?<br>( 56s ) Hope: {ChatWindowButton:Florida,Kansas,North Carolina,Other}<br>( 57s ) Visitor: Chat with a Care Advocate<br>( 59s ) Hope: I’m happy to connect you with a Care Advocate. Just a few things to note: If you’re having a medical emergency, call 911 instead. To provide you with the best care, the Care Advocate may ask you for additional demographic information. Do you understand?<br>( 1m 1s ) Hope: {ChatWindowButton:I Understand,Never Mind}<br>( 1m 6s ) Visitor: I Understand<br>( 1m 8s ) Hope: What is your first name?<br>( 1m 10s ) Hope: {ChatWindowButton:Never Mind}<br>( 1m 15s ) Visitor: Sufyaan<br>( 1m 17s ) Hope: What is your last name?<br>( 1m 19s ) Hope: {ChatWindowButton:Never Mind}<br>( 1m 23s ) Visitor: Virani<br>( 1m 25s ) Hope: What is your phone number?<br>( 1m 27s ) Hope: {ChatWindowButton:Never Mind}<br>( 1m 33s ) Visitor: 4074964710<br>( 1m 35s ) Hope: Your full name is &quot;Sufyaan Virani&quot;, is that correct?<br>( 1m 37s ) Hope: {ChatWindowButton:Yes,No}<br>( 1m 40s ) Visitor: Yes<br>( 1m 42s ) Hope: Lastly, to help us find resources relevant to you, what is your ZIP code?<br>( 1m 55s ) Visitor: 34711<br>( 1m 57s ) Hope: I am connecting you now.<br><p align="center">Agent Chatbot transferred the chat to QueueId 00G2M000003OwN3UAK</p><p align="center">Chat Started: Monday, November 02, 2020, 08:51:48 (-0500)</p><p align="center">Chat Origin: Coronavirus With Bot</p><p align="center">Chat Transferred From Hope To Jeff</p>( 2m 3s ) Jeff: Thank you for connecting with us. My name is Jeff. How can I care for you today?<br>( 2m 24s ) Visitor: Do I need a referral from my doctor to make a reservation first?<br>( 3m 4s ) Jeff: Good Morning Sufyaan! I will be happy to look into this for you.<br>( 3m 54s ) Jeff: Is your Doctor part of the Advent Health network?<br>( 5m 43s ) Visitor: I’m not sure<br>( 5m 53s ) Visitor: its dr shazia nasir<br>( 9m 13s ) Jeff: I am researching right now, one moment please.<br>( 10m 12s ) Visitor: No problem, do you cover Florida blue insurance?<br>( 16m 57s ) Jeff: Dr. Shazia Nasir is not part of the Advent Health network.  I would suggest calling your insurance company about questions with the referral. This number should be on the back of your insurance card.<br>( 17m 39s ) Visitor: Okay so I called and they said they don’t need referrals<br>( 17m 43s ) Visitor: just insurance info<br>( 17m 47s ) Visitor: could u confirm<br>( 18m 11s ) Jeff: If you would like to get connected with a specific Doctor within the Advent Health network, I would be happy to look into that for you.<br>( 20m 38s ) Jeff: I am unable to confirm because that physician is not with Advent Health. But the safest bet is to verify with your insurance provider .<br>( 21m 17s ) Jeff: Is there anything else I can assist you with?<br>( 24m 3s ) Visitor: That should be all<br>( 24m 20s ) Jeff: Thanks so much and have a great day!<br>'
posn = text.find(delim) + len(delim)
print(text[posn:])
s = re.sub('<.*?>|\(.*?\)', '', text[posn:])
print(s)

<br>( 2m 24s ) Visitor: Do I need a referral from my doctor to make a reservation first?<br>( 3m 4s ) Jeff: Good Morning Sufyaan! I will be happy to look into this for you.<br>( 3m 54s ) Jeff: Is your Doctor part of the Advent Health network?<br>( 5m 43s ) Visitor: I’m not sure<br>( 5m 53s ) Visitor: its dr shazia nasir<br>( 9m 13s ) Jeff: I am researching right now, one moment please.<br>( 10m 12s ) Visitor: No problem, do you cover Florida blue insurance?<br>( 16m 57s ) Jeff: Dr. Shazia Nasir is not part of the Advent Health network.  I would suggest calling your insurance company about questions with the referral. This number should be on the back of your insurance card.<br>( 17m 39s ) Visitor: Okay so I called and they said they don’t need referrals<br>( 17m 43s ) Visitor: just insurance info<br>( 17m 47s ) Visitor: could u confirm<br>( 18m 11s ) Jeff: If you would like to get connected with a specific Doctor within the Advent Health network, I would be happy to look into that for 

In [50]:
ca = 'Jeff'
visitor = ' Visitor: '
visitor = visitor.replace(' ', '\\s').replace(':', '\\:')
print(visitor)
re.findall('(\s((?!\s).)*?\:\s)', s)
re.findall('(' + visitor + '((?!' + ca + '\:).)*?' + ca + '\:\s)', s)

\sVisitor\:\s


[(' Visitor: Do I need a referral from my doctor to make a reservation first? Jeff: ',
  ' '),
 (' Visitor: I’m not sure Visitor: its dr shazia nasir Jeff: ', ' '),
 (' Visitor: No problem, do you cover Florida blue insurance? Jeff: ', ' '),
 (' Visitor: Okay so I called and they said they don’t need referrals Visitor: just insurance info Visitor: could u confirm Jeff: ',
  ' '),
 (' Visitor: That should be all Jeff: ', ' ')]

In [9]:
text = "Symptoms (0.68): Hi Courtney can u get a message of dr Desai I was exercising Friday lifting weights and doing stair master. Since then my lower back is in pain especially when I go to sleep every night. I’m not able to find a comfortable position because of the pain. And so it interferes with my sleeping. I would like to see if he can prescribe me something\
\
NO PREDICTION: Yes\
\n\
Scheduling (0.6): Ok I’m off work today so hopefully something can be done\
\n\
Feedback (0.77): So is this the portal I use to get messages to my doctor?This is the app\
\
Scheduling (0.48): That means I have to end this session I’m not able to do both\
"

In [10]:
text = re.findall('(\:\s.*?\n)', text)[0][2:-1]

In [6]:
arr = np.array([[5, 6], [7, 8]])
gfg = arr.flatten()
print( gfg ) 
print(gfg[::-1])

[5 6 7 8]
[8 7 6 5]


In [2]:
text.encode('utf-8').strip()

NameError: name 'text' is not defined

In [90]:

s = '<p align="center">Chat Started: Monday, November 02, 2020, 08:02:29 (-0500)</p>( 2s ) Hope: Hi, welcome to AdventHealth! I’m here to help you with any of the following options or to connect you with additional support.<br>( 4s ) Hope: What would you like help with?<br>( 6s ) Hope: {ChatWindowButton:COVID-19 Testing Reservations,Get Care Now,Access Medical Records,Talk with a Care Advocate}<br>( 17s ) ERIKA: null<br>( 19s ) Hope: I’m happy to connect you with a Care Advocate. Just a few things to note: If you’re having a medical emergency, call 911 instead. Are you ready?<br>( 21s ) Hope: {ChatWindowButton:I&#39;m Ready,Never Mind}<br>( 23s ) ERIKA: null<br>( 25s ) Hope: I am attempting to connect you now.<br><p align="center">Agent Chatbot transferred the chat to QueueId 00G2M000003OwN3UAK</p><p align="center">Chat Started: Monday, November 02, 2020, 08:03:08 (-0500)</p><p align="center">Chat Origin: Coronavirus With Bot</p><p align="center">Chat Transferred From Hope To Sheila</p>( 39s ) Sheila: Thank you for connecting with us. My name is Sheila. How can I care for you today?<br>( 1m 7s ) Sheila: Good Morning Erika, I here to assist you.<br>( 1m 9s ) ERIKA: Hi Sheila!<br>( 1m 43s ) ERIKA: Can you tell me where I could get a Covid test near me?<br>( 2m 18s ) Sheila: Hi Erika, I can help with that. Please send me your zip code and I can look up locations near you.<br>( 2m 25s ) ERIKA: 33896<br>( 2m 55s ) Sheila: Perfect, give me one moment while I look up locations.<br>( 3m 1s ) ERIKA: thanks<br>( 3m 54s ) Sheila: There is  AdventHealth Centra Care Orange Lake that is 7.08 miles away. <br>8201 W. Irlo Bronson Memorial Hwy<br>Kissimmee, FL 34747<br>(407) 465-0846<br>Hours: 8:00am to 8:00pm<br>( 4m 20s ) ERIKA: Perfect!<br>( 4m 57s ) Sheila: Would you like me to help you schedule an appointment? You can also download the Advent Health application and register for an appointment straight from your phone.<br>( 5m 19s ) Sheila: Here to support you :)<br>( 6m 27s ) ERIKA: I&#39;m ok right now, I just wanted to know the closest location. thanks.<br>( 6m 59s ) Sheila: Best of luck to you on your appointment and have a great day.<br>( 7m 18s ) ERIKA: Thank you! you, too. <br>'
s = '<p align="center">Chat Started: Monday, November 02, 2020, 08:34:52 (-0500)</p>( 2s ) Hope: Hi, welcome to AdventHealth! I’m here to help you with any of the following options or to connect you with additional support.<br>( 4s ) Hope: What would you like help with?<br>( 6s ) Hope: {ChatWindowButton:COVID-19 Testing Reservations,Get Care Now,Access Medical Records,Talk with a Care Advocate}<br>( 35s ) BERYL: null<br>( 38s ) Hope: I’m happy to connect you with a Care Advocate. Just a few things to note: If you’re having a medical emergency, call 911 instead. Are you ready?<br>( 40s ) Hope: {ChatWindowButton:I&#39;m Ready,Never Mind}<br>( 45s ) BERYL: null<br>( 47s ) Hope: I am attempting to connect you now.<br><p align="center">Agent Chatbot transferred the chat to QueueId 00G2M000003OwN3UAK</p><p align="center">Chat Started: Monday, November 02, 2020, 08:35:46 (-0500)</p><p align="center">Chat Origin: Coronavirus With Bot</p><p align="center">Chat Transferred From Hope To Liza</p>( 54s ) Liza: Thank you for connecting with us. My name is Liza. How can I care for you today?<br>( 1m 57s ) BERYL: I have an appointment at 2:30 pm but don’t remember where it was.<br>( 2m 59s ) Liza: Good morning Beryl, I would be more than happy to assist you with that information.<br>( 5m 13s ) Liza: If you allow me just a moment to look at your account and see what upcoming appointments you have.<br>( 6m 8s ) BERYL: Thank you <br>( 7m 3s ) Liza: Is the appointment with a specialist or with your primary care provider?<br>( 7m 51s ) BERYL: I don’t know <br>( 8m 40s ) Liza: Ok, no problem! We&#39;ll do our best to find the right information!<br>( 11m 29s ) Liza: Thank you for your patience. I am seeing two appointments in the system. One is a virtual appointment scheduled for tomorrow Tuesday November 3rd with Dr. Shalimar Delgado Perez at 1:45 PM.<br>( 12m 59s ) Liza: The second appointment I see scheduled is for Wednesday November 4 at 3:20 PM with Advent Health Imaging in Winter Garden.<br>( 15m 30s ) Liza: Here is the address for the appointment on Wednesday. 2200 Fowler Grove Blvd Winter Garden, FL 34787. Phone number is 407-614-0565.<br>( 16m 34s ) Liza: It was a pleasure being able to help you today. I hope you have a wonderful rest of your day. Thank you for choosing Advent Health.<br>( 16m 51s ) BERYL: Thank you, for helping. Have a great day be safe.<br>( 21m 18s ) Liza: Correct, your virtual appointment is tomorrow at 1:45 PM.  The phone number for doctor Delgado-Perez is 407-646-7070.<br>( 21m 57s ) Liza: The other appointment is for Wednesday the 4th at 3:20. That one is in person at the Advent Health Imaging in Winter Garden.<br>( 25m 34s ) BERYL: I can’t find it. I have a Virtual one tomorrow at 1:45p.m. The other one is the 4th Advent Health Imaging 3:20pm Winter Garden 2200 Fowler Blvd. 34787<br>( 26m 15s ) Liza: Do you have the Advent Health app on your phone?<br>'
s = '<p align="center">Chat Started: Monday, November 02, 2020, 10:11:49 (-0500)</p>( 2s ) Hope: Hi, welcome to AdventHealth! I’m here to help you with any of the following options or to connect you with additional support.<br>( 4s ) Hope: What would you like help with?<br>( 6s ) Hope: {ChatWindowButton:COVID-19 Testing Reservations,Get Care Now,Access Medical Records,Talk with a Care Advocate}<br>( 1m 33s ) DENNIS: checking in to see what you can do about my us anesthesia bill of 1722.00. <br>( 1m 35s ) Hope: I apologize for not understanding you. I&#39;m still learning.<br>( 1m 37s ) Hope: What would you like help with?<br>( 1m 39s ) Hope: {ChatWindowButton:COVID-19 Testing Reservations,Get Care Now,Access Medical Records,Talk with a Care Advocate}<br>( 1m 50s ) DENNIS: null<br>( 1m 52s ) Hope: I’m happy to connect you with a Care Advocate. Just a few things to note: If you’re having a medical emergency, call 911 instead. Are you ready?<br>( 1m 54s ) Hope: {ChatWindowButton:I&#39;m Ready,Never Mind}<br>( 1m 56s ) DENNIS: null<br>( 1m 58s ) Hope: I am attempting to connect you now.<br><p align="center">Agent Chatbot transferred the chat to QueueId 00G2M000003OwN3UAK</p><p align="center">Chat Started: Monday, November 02, 2020, 10:13:54 (-0500)</p><p align="center">Chat Origin: Coronavirus With Bot</p><p align="center">Chat Transferred From Hope To Vivianne</p>( 2m 6s ) Vivianne: Thank you for connecting with us. My name is Vivianne. How can I care for you today?<br>( 3m 4s ) DENNIS: Emily told me to contact her today concerning a bill I received. <br>( 4m 41s ) Vivianne: To better assist you may I ask, Who is Emily?<br>( 6m 2s ) DENNIS: She contacted me thru the Carium app and said contact today would start thru this app. <br>( 6m 54s ) Vivianne: Awesome! I believe you are already in our system! Did you get a chance to update your app?<br>( 8m 57s ) DENNIS: I uploaded advent health app. what do you mean by update?<br>( 11m 36s ) Vivianne: May I get the name of your physician?<br>( 12m 18s ) DENNIS: Dr Conroy<br>( 13m 20s ) Vivianne: To confirm, is it Dr. Lauren Conroy?<br>( 13m 26s ) DENNIS: yes<br>( 15m 11s ) Vivianne: Thank you for this information.<br>( 16m 28s ) Vivianne: By updating the AdventHealth app, you will be able to connect to your Care Advocate.<br>( 16m 59s ) Vivianne: It will automatically route you through the enrollment process<br>( 18m 34s ) DENNIS: Ok thanks<br>( 19m 10s ) Vivianne: Did I address all your concerns today?<br>( 19m 25s ) DENNIS: yes<br>( 20m 2s ) Vivianne: Awesome! Have a wonderful day!<br>'
#s = '<p align="center">Chat Started: Monday, November 02, 2020, 17:42:56 (+0000)</p>( 2s ) Hope: Hi, welcome to AdventHealth! I’m here to help you with any of the following options or to connect you with additional support.<br>( 4s ) Hope: What would you like help with?<br>( 6s ) Hope: {ChatWindowButton:COVID-19 Testing Reservations,Get Care Now,Access Medical Records,Talk with a Care Advocate}<br>( 1m 0s ) Dorlen: I need a refill prescription for my medicine sent to Morgan’s Pharmacy <br>( 1m 2s ) Hope: I apologize for not understanding you. I&#39;m still learning.<br>( 1m 4s ) Hope: What would you like help with?<br>( 1m 6s ) Hope: {ChatWindowButton:COVID-19 Testing Reservations,Get Care Now,Access Medical Records,Talk with a Care Advocate}<br>( 1m 20s ) Dorlen: null<br>( 1m 22s ) Hope: I’m happy to connect you with a Care Advocate. Just a few things to note: If you’re having a medical emergency, call 911 instead. Are you ready?<br>( 1m 24s ) Hope: {ChatWindowButton:I&#39;m Ready,Never Mind}<br>( 1m 32s ) Dorlen: null<br>( 1m 34s ) Hope: I am attempting to connect you now.<br><p align="center">Agent Chatbot transferred the chat to QueueId 00G2M000003OwN3UAK</p>'

In [73]:
import re
#delim = "How can I care for you today?"
start = "Thank you for connecting with us. My name is "
delim = ". How can I care for you today?"
print(s.find(start), s.find(delim))
ca_name = s[s.find(start)+len(start):s.find(delim)]
print(ca_name)
if len(ca_name) > 0:
    print("String")
print(ca_name)
s = str(s)[s.find(delim)+len(delim):]
s = s.replace('<br>', '\n')
#? in regex is for the closest match of '>' or ')'
s = re.sub('<.*?>|\(.*?\)', '', s)
s = re.sub(ca_name + ":(.*?)\n", "", s)
#df['Message'] = df['Message'].apply(lambda text: re.sub(r'[^a-z0-9A-Z\s]+','', str(text)))
print(s)

1398 1451
Vivianne
String
Vivianne



In [10]:
import csv
f = open("sample.csv", "w")
writer = csv.writer(f, quoting=csv.QUOTE_ALL)
#writer.writerows([["a", 1], ["b", 2]])
writer.writerows([[999], [12], [3330333333333399999999999999999]])
f.close()

In [9]:
import pandas as pd
import csv
df = pd.DataFrame([[999], [12], [3330333333333399999999999999999]], columns=['large_num'])
df['large_num'] = df['large_num'].astype(str).astype('string')
df.to_csv('temp.csv')
print(df.head())

df1 = pd.read_csv('temp.csv', dtype = object, index_col=0)
print(df1.head())
print([int(i) + 2 for i in df1['large_num']])

df2 = pd.read_csv('temp.csv', converters={0:str}, index_col=0)
print(df2.head())
print(int(df2['large_num'][2]) + 3)

                         large_num
0                              999
1                               12
2  3330333333333399999999999999999
                         large_num
0                              999
1                               12
2  3330333333333399999999999999999
[1001, 14, 3330333333333400000000000000001]
                         large_num
0                              999
1                               12
2  3330333333333399999999999999999
3330333333333400000000000000002


In [2]:
len("p align center Chat Started  Monday  November 02  2020  10 11 49  0500 p  2s   Hope  Hi  welcome to AdventHealth")

112

In [99]:
re.sub(r'[^a-z0-9A-Z\s]+',' ', s).strip()

'p align center Chat Started  Monday  November 02  2020  10 11 49  0500 p  2s   Hope  Hi  welcome to AdventHealth  I m here to help you with any of the following options or to connect you with additional support br  4s   Hope  What would you like help with br  6s   Hope   ChatWindowButton COVID 19 Testing Reservations Get Care Now Access Medical Records Talk with a Care Advocate br  1m 33s   DENNIS  checking in to see what you can do about my us anesthesia bill of 1722 00   br  1m 35s   Hope  I apologize for not understanding you  I 39 m still learning br  1m 37s   Hope  What would you like help with br  1m 39s   Hope   ChatWindowButton COVID 19 Testing Reservations Get Care Now Access Medical Records Talk with a Care Advocate br  1m 50s   DENNIS  null br  1m 52s   Hope  I m happy to connect you with a Care Advocate  Just a few things to note  If you re having a medical emergency  call 911 instead  Are you ready br  1m 54s   Hope   ChatWindowButton I 39 m Ready Never Mind br  1m 56s   

In [34]:
ca_name = "Vivianne"
s1 = s.replace('<br>', ' \n')
s1 = ''
z = re.sub(ca_name + ":(.*?)\n", "", s1)
print(z)

In [4]:
print(pd.__version__)

1.0.5


In [ ]:
! pip install pandas --upgrade

In [5]:
int(123.4)

123

In [1]:
str([2,3,'df'])

"[2, 3, 'df']"

In [6]:
from shutil import copyfile
copyfile("test.ipynb", "junk")

'junk'

In [1]:
def fun(x, a, b, c, d, y):
    print(x, a, b, c, d, y)
 
# Driver Code
my_list = [1, 2, 3, 4]
 
# Unpacking list into four arguments
fun(10, *my_list, 20)

10 1 2 3 4 20


In [1]:
msgs = msgs_clean = ""
msgs = "def"
print(msgs, msgs_clean)

def 


In [6]:
[x,r]=[2,3]
print(x,r)

2 3


In [3]:
# indices of top two elements
arr = np.array([5,6,7,2,1,9,23,44,8,45,2,6])
print(arr[3:5])
(-arr).argsort()[:2]

[2 1]


array([9, 7], dtype=int64)

In [2]:
",".join(['d','rt','we'])

'd,rt,we'

In [3]:
both = True
if both==False:
    print("a")

In [5]:
''.split(' ')

['']

In [3]:
columns=["Id", "bb Text", "aaabb", "bbb"]
df = pd.DataFrame(columns=columns)
df.loc[0] = [1,2,3,4]
print(df.columns[1:3])
for index, row in df.iterrows():
    print(row.values[1:3])

Index(['bb Text', 'aaabb'], dtype='object')
[2 3]


In [9]:
print(pd.Series([12,2,2,3]).unique())

[12  2  3]


In [12]:
import itertools
a = [['a','b'], ['c'], [34, 5, 6, 7]]
print(list(itertools.chain.from_iterable(a)))

['a', 'b', 'c', 34, 5, 6, 7]


In [7]:
import simple_icd_10 as icd
import icd10

print(icd.is_valid_code("S86"))
code = icd10.find("S86")
print(code.description)         # Acute bronchitis due to Mycoplasma pneumoniae

True
Injury of muscle, fascia and tendon at lower leg level


In [23]:
for code_str in icd.get_descendants("S86"):
    if icd.is_valid_code(code_str) and icd10.find(code_str) != None:
        print(code_str, icd10.find(code_str).description)

ValueError: S8 is not a valid ICD-10 code.

In [43]:
import simple_icd_10 as icd
import icd10
import regex as re

for code_str in icd.get_all_codes(True):
    if icd10.find(code_str) != None:
        desc = icd10.find(code_str).description
        match = re.search(r'J..\.', code_str)
        #if "injury" in desc:
        if match:
            print(code_str, desc)

J01.0 Acute maxillary sinusitis
J01.1 Acute frontal sinusitis
J01.2 Acute ethmoidal sinusitis
J01.3 Acute sphenoidal sinusitis
J01.4 Acute pansinusitis
J01.8 Other acute sinusitis
J01.9 Acute sinusitis, unspecified
J02.0 Streptococcal pharyngitis
J02.8 Acute pharyngitis due to other specified organisms
J02.9 Acute pharyngitis, unspecified
J03.0 Streptococcal tonsillitis
J03.8 Acute tonsillitis due to other specified organisms
J03.9 Acute tonsillitis, unspecified
J04.0 Acute laryngitis
J04.1 Acute tracheitis
J04.2 Acute laryngotracheitis
J05.0 Acute obstructive laryngitis [croup]
J05.1 Acute epiglottitis
J06.0 Acute laryngopharyngitis
J06.9 Acute upper respiratory infection, unspecified
J10.0 Influenza due to other identified influenza virus with pneumonia
J10.1 Influenza due to other identified influenza virus with other respiratory manifestations
J10.8 Influenza due to other identified influenza virus with other manifestations
J11.0 Influenza due to unidentified influenza virus with p

In [44]:
print(len(icd.get_all_codes(True)))

12542


In [10]:
print((datetime.today().date() - datetime.today().date()).days)

0


In [1]:
x = [2,3]
x.append(3)
print(x)

[2, 3, 3]


In [25]:
img = np.array([[1,2],[3,4]])
np.repeat(img[..., np.newaxis],3,-1)
np.repeat(img,3,1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [1]:
"s/d/f/g".split("/")[-1]

'g'

In [1]:
# Three ways to double a list
x = [2,3,1]

print([2*y for y in x])

l = []
for y in x:
    l.append(2*y)
print(l)

import numpy as np
print(list(2 * np.array(x)))

[4, 6, 2]
[4, 6, 2]
[4, 6, 2]


In [8]:
x=pd.DataFrame([2,3,5], columns=['a'])
x.head()

a
0  2
1  3
2  5

In [13]:
x[['c','d']] = [[2,2],[7,4],[5,8]]
x.head()

a  c  d
0  2  2  2
1  3  7  4
2  5  5  8

In [15]:
[1,'f'] + [2,3,4]

[1, 'f', 2, 3, 4]

In [7]:
# Define a dictionary containing students data
data = {'Name': ['Ankit', 'Amit', 'Aishwarya', 'Priyanka'],
                'Age': [21, 19, 20, 18],
                'Stream': ['Math', 'Commerce', 'Arts', 'Biology'],
                'Percentage': [88, 92, 95, 70]}
  
# Convert the dictionary into DataFrame
df = pd.DataFrame(data, columns = ['Name', 'Age', 'Stream', 'Percentage'])
  
print("Given Dataframe :\n", df)
  
print("\nIterating over rows using iterrows() method :\n")
  
# iterate through each row and select 
# 'Name' and 'Age' column respectively.
for index, row in df.iterrows():
    print (row.values[0])
list(df.loc[1][['Name','Age']])

Given Dataframe :
         Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20      Arts          95
3   Priyanka   18   Biology          70

Iterating over rows using iterrows() method :

Ankit
Amit
Aishwarya
Priyanka


['Amit', 19]

In [1]:
import calendar
from datetime import date, datetime, timedelta
from dateutil.relativedelta import relativedelta
start_date = datetime(2021, 3, 10).date()

delta = calendar.monthrange(start_date.year, start_date.month)[1] - start_date.day
start_date = start_date + timedelta(days=delta)
print(start_date)

2021-03-31


In [22]:
a = np.array((1,2,3))
print(a)
if not all(i <= 3 for i in a):
    print('error')

[1 2 3]


In [1]:
"asdf sd".contains('sd')

AttributeError: 'str' object has no attribute 'contains'

In [ ]:
txt = "1-7. (Canceled) \
8. (Currently Amended) A method of electronically distributing a press \
release, the press release comprising a message comprising an advertiser sponsored \
content, from a server computer to one or more forum sites over a global computer."

match = re.search(str(8) + "\.(.+?)\.", txt)
clm_text = match.group(1)
print(clm_text)

In [ ]:
print(re.search(str(8) + "\.(.+?)\.", txt).group(1))
flag = re.search(r"(A2)|([0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9])", "US 2006/0190333 A1 08-24-2006 Choi")
if flag:
    print(flag.group())
    print(flag.group(1))
    print(flag.group(2))

In [ ]:
class_regex = "([0-9]+/[0-9]+)"
flag = re.search(class_regex, "1/45")
print(flag.group())

In [3]:
int(10/3)

3